# version: '3.8'

services:
  backend:
    build: .
    # command: ping 127.0.0.1
    # command: python -m core.bot
    command: scripts/entrypoint.sh
    container_name: rlt-backend
    volumes:
      - .:/app
      - assets_volume:/app/assets
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: rlt-postgres
    env_file:
      - dev.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  assets_volume:
